version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/marqueswsm/webapi-go
    container_name: webapi-go-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/webapi-go
    volumes:
      - webapp:/var/lib/postgresql/data

volumes:
  webapi-mvc:
